apiVersion: v1
kind: Secret
metadata:
  name: hooli-heard-secret
  namespace: hooli-heard
type: Opaque
stringData:
  POSTGRES_PASSWORD: hooli-heard-2026
  DATABASE_URL: postgresql://hooli:hooli-heard-2026@postgres:5432/hooliheard
